name: Pylint, Black Formatter, Pytest

on:
  push:
    branches: [talals_branch, ahmeds_branch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install black
        pip install pytest
        pip install -r requirements.txt
        echo "STARTING TEST NOW"
    - name: Running black Formatter
      run: |
        black app.py
        echo "Black has formatted app.py"
    - name: Analysing the code with pylint
      run: |
        pylint app.py
        echo "TEST WENT VIRAL"
    - name: Testing 404 Page
      run: |
        python -m pytest

  build2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Set up CodeQL
      uses: github/codeql-action/setup@v1
      with:
        languages: python
        auto-configure: true

    - name: Build CodeQL database
      run: |
        codeql database create codeql-db --language=python --command='python app.py'
    
    - name: Analyze code with CodeQL
      run: |
        codeql database analyze codeql-db python-code-scanning.qls --format=sarif-latest --sarif-output=codeql-results.sarif
    
    - name: Upload results
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: codeql-results.sarif
